# Generated by Django 5.1.3 on 2024-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0003_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dislikes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
